### ISSUE TITLE
Offline mode - use AGSFeatureTableLayer

### ISSUE THREAD

**Issue by vladimirimr** [nixta/clusterlayer-plugin-ios#21]
Cau we use this for offline data also 
AGSFeatureTableLayer? and is it possible to update.

**Comment by nixta** [comment]
Hi @vladimirimr,

I'll take a look but it should be straightforward. I think I built it to be independent of data source, though I might need to finish some refactoring.

will set myself a reminder to dig in after Dev Summit.

**Comment by nixta** [comment]
Hi @vladimirimr: Take a look at [this commit](https://github.com/nixta/clusterlayer-plugin-ios/commit/c5c7185105718b0c2b0bf18ce40e2213682d4449) on [this branch](https://github.com/nixta/clusterlayer-plugin-ios/tree/runtime-geodatabase).

It's a rough-and-ready first stab I did on the train yesterday. I will test it some more and tidy it up.

You may want to disable the additional dummy graphics data that [gets added in the viewController's mapView:didLoad delegate method](https://github.com/nixta/clusterlayer-plugin-ios/blob/runtime-geodatabase/Sample/Source/AGSSampleViewController.m#L108-L134).

Let me know how this works for you.

Nick.

**Comment by vladimirimr** [comment]
Hi @nixta,  
Yes great work, tnx. I was on good track I knew that I had to include queryResultsWithParameters, but after that I was little lost, didn't know how to parse AGSGDBFeature into AGSGraphic, you give me a deeper look into it. 
Once more I really appreciate your effort.

**Comment by nixta** [comment]
Great stuff. Yeah. This whole aspect of things should be much cleaner in Quartz (separate hierarchies for offline and online class families will go, I believe).

Glad this helped!
